### ISSUE TITLE
persist the pages of bottom nav..

### ISSUE THREAD

**Issue by dubey2k** [TheAlphamerc/flutter_twitter_clone#135] opened 2021-02-09 08:09 UTC
I have installed the app and observed that there is no state persistence in the screens of bottom nav.
I think it should be implemented, its too irritating if someone is navigated to the very top of feed. 

1. open app
2. Click on one of the bottom nav item
3. Scroll down few posts
4. jump to other bottom nav item
5. move to previous nav item

Expected behavior:
It should preserve the states of all the nav items.

**Comment by TheAlphamerc** [comment] 2021-03-03 04:41
Duplicate of https://github.com/TheAlphamerc/flutter_twitter_clone/issues/63

**Closed by TheAlphamerc** 2021-03-03 04:41 UTC
