### ISSUE TITLE
Hi, I just installed the application to learn about Flutter. I've been 2 hours and I keep getting an error when putting them into operation

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [TheAlphamerc/flutter_twitter_clone#215] opened 2021-11-08 19:41 UTC
**Describe the bug**
Hi, I just installed the application to learn about Flutter. I've been 2 hours and I keep getting an error when putting them into operation

Because flutter_link_preview 1.5.6 depends on http ^0.12.1 and no versions of flutter_link_preview match >1.5.6 <2.0.0, flutter_link_preview ^1.5.6 requires http ^0.12.1.
So, because flutter_twitter_clone depends on both flutter_link_preview ^1.5.6 and http ^0.13.3, version solving failed.
pub get failed (1; So, because flutter_twitter_clone depends on both flutter_link_preview ^1.5.6 and http ^0.13.3, version solving failed.)

**To Reproduce**

**Expected behavior**

Will run the application
**Screenshots**

**Smartphone (please complete the following information):**
 ALL DEVICE

**App**
- version[e.g.  1.0.4]

**Additional context**

**Comment by TheAlphamerc** [comment] 2021-11-18 14:58
Duplicate of https://github.com/TheAlphamerc/flutter_twitter_clone/issues/216#issue-1052936252

**Closed by TheAlphamerc** 2021-11-18 14:58 UTC
Labels: duplicate
