### ISSUE TITLE
Can't run app on android after add qrScaner

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#136] opened 2021-03-09 00:52 UTC
![Screenshot 2021-03-09 at 01 51 07](https://user-images.githubusercontent.com/53181006/110401554-0c8f1080-807a-11eb-97b1-8dad732aeae9.png)

**Comment by TheAlphamerc** [comment] 2021-03-09 12:40
@qwerty684 While compiling code make sure you have active and good internet connection. This error occurred when a package download failed while compiling code.

**Comment by qwerty684** [comment] 2021-03-09 16:02
@TheAlphamerc  I have good connection, but this error is still here, when I try to run for iOS device this work without any problem, but on android is like this, even if I want to build apk..

**Comment by TheAlphamerc** [comment] 2021-03-11 09:46
@qwerty684 Can you try `flutter build clean` command and restart the IDE and then try to recompile again?

**Comment by TheAlphamerc** [comment] 2021-03-13 12:18
@qwerty684 which version of flutter you are using ?

**Comment by qwerty684** [comment] 2021-03-13 13:52
@TheAlphamerc  Here you can seen.
![Screenshot 2021-03-13 at 14 51 50](https://user-images.githubusercontent.com/53181006/111032275-a7397780-840b-11eb-8992-8ec36cdf9056.png)

**Comment by TheAlphamerc** [comment] 2021-03-14 16:05
Upgrade your flutter sdk version to 2.0.0 and then try it.

**Comment by qwerty684** [comment] 2021-03-16 20:26
@TheAlphamerc Still same, now also can't run on my iOS device also..

**Comment by TheAlphamerc** [comment] 2021-05-30 07:53
@ublockme did you face the same issue ever ?

**Comment by TheAlphamerc** [comment] 2021-07-24 04:22
@qwerty684  It's been a long time since you created the issue and I am not able to reproduce the error. so closing the issue for now.

**Closed by TheAlphamerc** 2021-07-24 04:22 UTC
