### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by Curiosity324** [TheAlphamerc/flutter_twitter_clone#34] opened 2020-05-13 14:46 UTC
I suggest you add file sharing capabilities to the chat section

**Comment by TheAlphamerc** [comment] 2020-05-13 16:53
Thanks for the suggestion. I am planning to implement this in a future release.

**Comment by elcolie** [comment] 2020-08-06 16:50
I propose support on REST API database and generic websocket connection
Because I made backend already now. I am copying your UI to my app

**Comment by Dhua-v** [comment] 2020-08-06 16:59
Hy, @elcolie  I was also desiring to do same. Can we take up this suggestion of yours to implementation.

**Comment by Dhua-v** [comment] 2020-08-07 06:07
So is there some design documentation for the set of apis or socket format.

**Comment by elcolie** [comment] 2020-08-07 17:36
APIs: Feel free to shoot my backend since it has on one in there [postman](https://www.getpostman.com/collections/6730832b2d84b46d2e12)
Socket haven't started yet. My project was freeze by money shortage. Therefore I have to start over the `Flutter`
in order to take care of android, ios, and website by myself. I have enough with ReactJs, React Native, and Swift5

Let me know your implementation then I can support your APIs part and I can start working on `socket` as well

**Comment by TheAlphamerc** [comment] 2020-08-08 07:27
@elcolie just checked your postman APIs and I am really amazed to see them. You have done a great job. 
I have a few queries 
1. Can you let me know in which technology you have created these APIs? 
2. The source code of the APIs are open source? if not are you planning to do so?
3. Have you integrated these APIs in any frontend application?

**Comment by TheAlphamerc** [comment] 2020-11-09 11:21
Duplicate of https://github.com/TheAlphamerc/flutter_twitter_clone/issues/97

**Closed by TheAlphamerc** 2020-11-09 11:21 UTC
Labels: enhancement
