### ISSUE TITLE
Snackbar Deprecation error

### ISSUE THREAD

**Issue by shuaibidshuaib** [TheAlphamerc/flutter_twitter_clone#191] opened 2021-07-09 11:04 UTC
**The snackbar in fluter twitter clone shows deprecation error**
Here is the code and pls show me the code, that will stop showing such errors. please help me.

static customSnackBar(GlobalKey<ScaffoldState> _scaffoldKey, String msg,
      {double height = 30, Color backgroundColor = Colors.black}) {
    if (_scaffoldKey == null || _scaffoldKey.currentState == null) {
      return;
    }
    _scaffoldKey.currentState.hideCurrentSnackBar();
    final snackBar = SnackBar(
      backgroundColor: backgroundColor,
      content: Text(
        msg,
        style: TextStyle(
          color: Colors.white,
        ),
      ),
    );
    _scaffoldKey.currentState.showSnackBar(snackBar);
  }.
Also im using flutter sdk version 2.0.6 , and when i compile and open app, it satys in the snackbar session continuously without proceeding to the signup page, i dont know if this has to deal with sdk or snackbar deprecation, i observed this in both debug mode and release mode, pls help me to solve this issues, im currently stuck.

**Comment by TheAlphamerc** [comment] 2021-07-09 12:02
Duplicate of https://github.com/TheAlphamerc/flutter_twitter_clone/issues/190

**Closed by TheAlphamerc** 2021-07-09 12:02 UTC
Labels: duplicate
